# Generated by Django 6.0.2 on 2026-02-11 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('video_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos_img/')),
                ('publicado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CursoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.clase')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cursos.curso')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('curso', 'orden')},
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='clases',
            field=models.ManyToManyField(related_name='cursos', through='cursos.CursoClase', to='cursos.clase'),
        ),
    ]
